# server
server:
 port: 8888
 
# DB
spring:
 datasource:
  url: jdbc:oracle:thin:@211.105.15.179:1521:xe
  username: PAPERHOUSE
  password: PAPERHOUSE
  driver-class-name : oracle.jdbc.OracleDriver
   
